# Generated by Django 5.0 on 2023-12-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogger_Profile',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='Viewer_Profile',
        ),
    ]
